In [5]:
import numpy as np

In [6]:
vetor = np.array([10, 20, 30, 40, 50])
vetor

array([10, 20, 30, 40, 50])

In [7]:
matriz2d = np.array([[10, 20], [4, 5]])
print(matriz2d)

[[10 20]
 [ 4  5]]


In [8]:
matriz2d = np.array([[10, 20, 30], [4, 5, 6]])
print(matriz2d)

[[10 20 30]
 [ 4  5  6]]


In [2]:
import pandas as pd


In [3]:
# Estrutura unidimensional com pandas series:

s1 = pd.Series([10, 20, 30, 40, 50], name="Serie 1")
s2 = pd.Series([1, 2, 3, 4, 5], name="Serie 2")

s_soma = s1 + s2
s_sub = s1 - s2
s_mult = s1 * s2
s_div = s1 / s2

print(s_soma)
print(s_sub)
print(s_mult)
print(s_div)


0    11
1    22
2    33
3    44
4    55
dtype: int64
0     9
1    18
2    27
3    36
4    45
dtype: int64
0     10
1     40
2     90
3    160
4    250
dtype: int64
0    10.0
1    10.0
2    10.0
3    10.0
4    10.0
dtype: float64


In [4]:
df = pd.DataFrame({'Serie 1': s1, 'Serie 2': s2})
df

Serie 1  Serie 2
0       10        1
1       20        2
2       30        3
3       40        4
4       50        5

In [9]:
df['Soma'] = df['Serie 1'] + df['Serie 2']
df['Subtracao'] = df['Serie 1'] - df['Serie 2']
df

Serie 1  Serie 2  Soma  Subtracao
0       10        1    11          9
1       20        2    22         18
2       30        3    33         27
3       40        4    44         36
4       50        5    55         45

In [10]:
s1 = pd.Series([10, 20, 30, 40, 50], name="Serie 1")
s2 = pd.Series([1, 2, 3, 4, 5], name="Serie 2")
s3 = pd.Series(['A', 'B', 'C', 'B', 'A' ], name="Serie 3")

df = pd.DataFrame({'Serie 1': s1, 'Serie 2': s2, 'Serie 3': s3})
df

Serie 1  Serie 2 Serie 3
0       10        1       A
1       20        2       B
2       30        3       C
3       40        4       B
4       50        5       A

In [ ]:
df.groupby('Serie 3')['soma'].max() # maximo
df.groupby('Serie 3')['soma'].min() # mínimo
df.groupby('Serie 3')['soma'].mean() # média
df.groupby('Serie 3')['soma'].median() # mediana
df.groupby('Serie 3')['soma'].std() # desvio padrão


In [13]:
# 1) Crie um pandas Series contendo números de 1 a 10

s1 = pd.Series(range(1,11))
print(s1)

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64


In [14]:
# 2) Acesse o Terceiro elemento de uma Pandas Series e imprima seu valor

s1[2]

3

In [15]:
# 3) Some duas Pandas Series contendo os números de 1 a 5 e os números de 6 a 10 respectivamente

s1 = pd.Series(range(1,6))
s2 = pd.Series(range(6,11))

soma = s1 + s2
print(soma)

0     7
1     9
2    11
3    13
4    15
dtype: int64


In [16]:
# 4) Crie uma Pandas Series contendo os números de 1 a 10 e exiba apenas os valores maiores que 5.

s3 = pd.Series(range(1,11))

for s in s3:
    if s >= 5:
        print(s)

# ou --> s3[s3>5]

5
6
7
8
9
10


In [ ]:
# 5) Calcule a media e o desvio padrão de uma Pandas Series contendo os números de 1 a 10

s4 = pd.Series(range(1,11))
media = s4.mean()
print(f'A média é: {media}')

desvio_padrao = s4.std()
print(f'O desvio padrão é: {desvio_padrao}')

In [ ]:
# 6) Concatene duas Pandas Series contendo números de 1 a 5 e 6 a 10, respectivamente, em uma única series

s5 = pd.Series(range(1,6))
s6 = pd.Series(range(6,11))

serie_concatenada = pd.concat([s5,s6], axis=1)
print(serie_concatenada)

In [ ]:
# 7) Subtraia uma Pandas Series contendo os números de 1 a 10 por uma outra Series contendo os números de 10 a 1

s10 = pd.Series(range(1,11))
s11 = pd.Series(range(10,0,-1))

sub = s10- s11
print(sub)

In [ ]:
# 8) Ordene uma Pandas Series contendo os números de 1 a 10 em ordem crescente

s12 = pd.Series(range(1,11))
s12.sort_values(ascending= False)

In [17]:
# 9) Verifique se o pandas Series possui valores iguais

s1 = pd.Series([10,20,20,30,40,50,50], name = 'Serie 1')
s1.duplicated()

0    False
1    False
2     True
3    False
4    False
5    False
6     True
Name: Serie 1, dtype: bool